# Generated by Django 4.1.4 on 2022-12-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('age', models.PositiveIntegerField()),
                ('specialization', models.CharField(max_length=64)),
                ('educational_institution', models.CharField(max_length=64)),
                ('id_num', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('age', models.PositiveIntegerField()),
                ('disease', models.CharField(max_length=64)),
                ('id_num', models.PositiveIntegerField()),
                ('smoking', models.BooleanField()),
            ],
        ),
    ]
