# Generated by Django 4.1.4 on 2022-12-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_doctor_experience_doctor_gender_patient_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='id_num',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_num',
            field=models.BigIntegerField(max_length=9),
        ),
    ]
