# Generated by Django 4.1.4 on 2022-12-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_appointments_created_remove_appointments_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='doctorId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='patientId',
            field=models.IntegerField(null=True),
        ),
    ]
