# Generated by Django 4.1.4 on 2022-12-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_patient_id_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
