# Generated by Django 4.1.4 on 2023-01-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_appointments_doctorid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('phone', models.CharField(max_length=40, null=True)),
                ('email', models.EmailField(max_length=40, null=True)),
                ('subject', models.CharField(max_length=40, null=True)),
                ('message', models.TextField(max_length=40, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Appointments',
        ),
    ]
