# Generated by Django 4.1.4 on 2022-12-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_appointments_doctorid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='doctorId',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='patientId',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
