# Generated by Django 4.1.4 on 2022-12-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_delete_appointments_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_date', models.DateField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField()),
                ('address', models.CharField(max_length=64)),
                ('symptoms', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-sent_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='accepted_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='sent_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='symptoms',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='time',
        ),
    ]
