# Generated by Django 4.1.4 on 2022-12-31 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_room_alter_appointments_doctorid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
