# Generated by Django 4.1.4 on 2022-12-30 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_appointments_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointments',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='sent_date',
            new_name='date',
        ),
    ]
