# Generated by Django 4.1.4 on 2023-01-02 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_message_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
