# Generated by Django 4.1.4 on 2022-12-30 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_appointments_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointments',
            new_name='Appointment',
        ),
    ]
