# Generated by Django 4.1.4 on 2023-01-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_delete_message_delete_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='patientId',
        ),
        migrations.AddField(
            model_name='appointments',
            name='patient_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
