# Generated by Django 4.1.4 on 2022-12-30 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_appointments_appointment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-dte']},
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='dte',
        ),
    ]
