# Generated by Django 4.1.4 on 2022-12-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='dte',
            field=models.DateField(),
        ),
    ]
