# Generated by Django 4.1.4 on 2023-01-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_appointments_patientid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='appointmentDate',
            new_name='appointment_date',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='patient_name',
            new_name='patient_email',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='doctorId',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='doctorName',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='patientName',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='status',
        ),
        migrations.AddField(
            model_name='appointments',
            name='appointment_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='patient_first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='patient_last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='patient_phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
