# Generated by Django 4.1.4 on 2022-12-30 15:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_appointment_dte'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_of_the_month',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
