# Generated by Django 4.1.4 on 2023-01-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_appointments_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
