# Generated by Django 4.1.4 on 2022-12-31 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_doctor_doctor_of_the_month'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
