# Generated by Django 4.1.4 on 2023-01-04 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_appointments_appointment_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointments',
            new_name='Appointment',
        ),
    ]
