# Generated by Django 4.1.4 on 2023-01-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, null=True)),
                ('last_name', models.CharField(max_length=40, null=True)),
                ('email', models.EmailField(max_length=40, null=True)),
                ('address', models.TextField(max_length=40, null=True)),
                ('phone', models.CharField(max_length=40, null=True)),
                ('blood_type', models.CharField(max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('phone', models.CharField(max_length=40, null=True)),
                ('email', models.EmailField(max_length=40, null=True)),
                ('subject', models.CharField(max_length=40, null=True)),
                ('message', models.TextField(max_length=40, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
