# Generated by Django 4.1.4 on 2023-01-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_appointment_message_room'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BloodDon',
            new_name='BloodDonation',
        ),
    ]
