# Generated by Django 4.1.4 on 2023-01-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_appointment_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient_email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_phone_number',
            field=models.BigIntegerField(max_length=50, null=True),
        ),
    ]
