# Generated by Django 4.1.4 on 2023-01-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_appointment_patient_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient_phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
