# Generated by Django 4.1.4 on 2023-01-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_doctor_first_name_remove_doctor_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=64, null=True),
        ),
    ]
