# Generated by Django 4.1.4 on 2023-01-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_doctor_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='password',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='username',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id_num',
            field=models.BigIntegerField(null=True),
        ),
    ]
