# Generated by Django 4.1.4 on 2023-01-09 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
