# Generated by Django 4.1.4 on 2023-01-11 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_blooddon_contactus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BloodDon',
            new_name='BloodDonation',
        ),
    ]
